version: '3'
services:  
  swtapp: #name of your application
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run dev